<%@ Page Title="" Language="C#" MasterPageFile="~/MCSMainMaster.master" AutoEventWireup="true" CodeFile="CurrencyInfo.aspx.cs" Inherits="CurrencyInfo" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<table width="98%" cellpadding="0" align="center" class="tblStyle">
        <tr>
            <td class="editmodetd">
                <asp:Label ID="lbleditmodeUserList" runat="server" Text="Currency Information Management" SkinID="editmodelabelskin"></asp:Label>
            </td>
        </tr>
        <tr>
            <td>
              <asp:ScriptManager ID="ScriptManager1" runat="server">
                </asp:ScriptManager>
                <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                 <ContentTemplate>
                    <table width="100%" class="tblStyleborderless" cellspacing="0" align="center">
                    <tr>
                        <td width="40%">
                            <table width="100%">
                                <tbody>
                                    <tr>
                                        <td class="captiontd">
                                            <asp:Label runat="server" ID="lblCurrencyName" Text="Currency Name "></asp:Label>
                                        </td>
                                        <td class="contenttd">
                                            <asp:TextBox runat="server" ID="txtCurrencyName" SkinID="fullsizedtextbox"></asp:TextBox>
                                            <asp:TextBox runat="server" ID="txtCurrencyId" Visible="false" SkinID="fullsizedtextbox"></asp:TextBox>
                                        </td>
                                        <td class="textmandatory">
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="captiontd">
                                            <asp:Label runat="server" ID="lblCountryList" Text="Country"></asp:Label>
                                        </td>
                                        <td class="contenttd">
                                            <asp:DropDownList Width="182px" runat="server" ID="drplstCountryList">
                                            </asp:DropDownList>
                                        </td>
                                        <td class="textmandatory">
                                            &nbsp;
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="captiontd">
                                        </td>
                                        <td class="contenttd">
                                            &nbsp;<asp:Button runat="server" CssClass="buttontype" ID="btnSave" Text="Save"
                                                CausesValidation="False" onclick="btnSave_Click" />
                                            <asp:Button ID="btnNew" runat="server" CausesValidation="False" 
                                                CssClass="buttontype" onclick="btnNew_Click" Text="New.." />
                                        </td>
                                        <td class="textmandatory">
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                        <td style="text-align: left">
                           
                        </td>
                    </tr>
                    <tr>
                        <td class="gridheadertd" colspan="2">
                            <asp:Label ID="lblGridHeader" runat="server" Text="Currency List" SkinID="gridheaderlableskin"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" align="center">
                            <asp:GridView ID="gvCurrencyInfoList" runat="server" 
                                AutoGenerateColumns="False" PageSize="5"
                                Width="100%" AllowPaging="True" 
                                onrowediting="gvCurrencyInfoList_RowEditing" 
                                AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                                onpageindexchanging="gvCurrencyInfoList_PageIndexChanging" 
                                onrowdeleting="gvCurrencyInfoList_RowDeleting">
                                <Columns>
                                    <asp:BoundField DataField="Id" HeaderText="Currency Id">
                                        <ItemStyle CssClass="hide" />
                                        <HeaderStyle CssClass="hide" />
                                    </asp:BoundField>
                                    <asp:BoundField DataField="CurrencyName" HeaderText="Currency Name"></asp:BoundField>
                                    <asp:BoundField DataField="CountryId" HeaderText="Country Id">
                                        <ItemStyle CssClass="hide" />
                                        <HeaderStyle CssClass="hide" />
                                    </asp:BoundField>
                                    <asp:BoundField DataField="CountryName" HeaderText="Country Name"></asp:BoundField>
                                </Columns>
                            </asp:GridView>
                        </td>
                    </tr>
                </table> 
                 </ContentTemplate>
                </asp:UpdatePanel>
                <asp:UpdateProgress ID="UpdateProgress1" runat="server" AssociatedUpdatePanelID="UpdatePanel1">
                 <ProgressTemplate>
                   <div>
                       <img src="Images/Progress.gif"
                       Please Wait...
                    </div>
                 </ProgressTemplate>
                </asp:UpdateProgress>
            </td>
        </tr>
    </table>
</asp:Content>

